name: Build mysql-router container image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: >
          The branch, tag or SHA to checkout and build.
        required: true
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}

      - name: Set up docker context for buildx
        run: |
          docker context create router-build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        run: |
          bash tag.sh | awk '{for (i=1;i<=NF;i++) {print "type=raw,value="$i} }' >> $GITHUB_OUTPUT
        id: img_tag
        working-directory: ./mysql-router

      - name: Set up docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/canozokur/mysql-router
          tags: |
            type=raw,value=${{ steps.img_tag.outputs.IMG_TAG }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: router-build

      - name: Build mysql-router
        uses: docker/build-push-action@v3
        with:
          context: mysql-router/8.0/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
